### ISSUE TITLE
Steady-state replacement is not really steady-state

### ISSUE THREAD

**Issue by jmmcd** [jmmcd/PonyGE2#50]
Our steady-state replacement just takes an old and new population and sorts, keeping the best. That's not the same as a steady-state algorithm, where one selects 2 individuals at a time, carries out mutation and/crossover, and inserts them to the population, replacing some individuals. It would be better to rename this operator, if we're keeping it.

**Comment by mikefenton** [comment]
Sounds good. Presumably the use of "proper" steady state replacement means the number of generations should be far higher than otherwise? As far as I can see (from our current implementation, that is), the only way to "correctly" implement steady state is to set 'params['GENERATION_SIZE']' to 2, which would mean selection creates a parent pop of size 2, x-over creates a pop of size 2, mutation mutates both inds, and then replacement would insert them back into the original population. This would constitute an entire "step" of the step function, but would only generate 2 inds. Does this sound correct?

**Comment by jmmcd** [comment]
I think that would be right... would like to check that carefully.

**Comment by dvpfagan** [comment]
New step function would sort it out be would mean you'd need -step
steadystate and -replacement steady state set as flags

I would vote leave as is and rename, or exclude from release.

Dave

**Comment by mikefenton** [comment]
I vote to change the current steady state implementation (i.e. add in to pop, sort, and remove worst) so that it replaces the original selected parents with the new inds regardless of fitness. Presumably this is the correct way to implement it? Then all we need to do is document it correctly in the Readme...

**Comment by jmmcd** [comment]
https://pdfs.semanticscholar.org/31d6/2b9bb357e8ab5cb757f6f834f9652b710754.pdf

https://books.google.co.uk/books?hl=en&lr=&id=3TqeBQAAQBAJ&oi=fnd&pg=PA94&dq=steady-state+genetic+algorithm&ots=Y49b2p85oy&sig=HW3iFCAkEFfM5PT6sZsLnJZLvEA#v=onepage&q=steady-state%20genetic%20algorithm&f=false

**Comment by dvpfagan** [comment]
It doesn't replace its parents it replaces the worst inds in the population

Steady-state replacement was first used by Whitley on the Genitor algorithm

(Whitley, 1989). In this scheme, two individuals are selected from the
population

(using any available selection algorithm), and genetic operators are
applied. The

resulting offspring then replace the worst members of the current
population. In

overlapping schemes such as this (where offspring are allowed to mate with
their

parents), a generation is deemed complete when n individuals are replaced
with
new offspring, where n is the size of the population.
