### ISSUE TITLE
Incorporate a scripts folder

### ISSUE THREAD

**Issue by dvpfagan** [jmmcd/PonyGE2#51]
Should we add a folder on the dataset and src level called scripts which can house the stats parser and possibly an experiment manager?

**Comment by jmmcd** [comment]
Yes -- and ponyge.py itself.

**Comment by mikefenton** [comment]
Stats parser now lives in scripts folder. Ponyge.py was moved there, but there are conflicting ideas about where it should live (in /src or in /scripts). Answers on a postcard please.

**Comment by mikefenton** [comment]
Stripped out and cleaned the experiment manager, added it back to the scripts folder. We now provide a basic experiment manager and stats parser. In terms of use, it's exactly the same as calling a normal PonyGE run (i.e. you can give params from the command line, through a params file, or by editing the params dict yourself). The number of runs can be set with `--runs`. 

The only remaining question is whether or not to include the main `ponyge.py` file in the scripts folder or to leave it in `\src`. Thoughts?

**Comment by dvpfagan** [comment]
Leave in src as it currently stands is my vote

**Comment by dvpfagan** [comment]
http://stackoverflow.com/questions/193161/what-is-the-best-project-structure-for-a-python-application

**Comment by mikefenton** [comment]
The current setup looks good, closing this issue.

**Comment by mikefenton** [comment]
Just adding to this to state that we currently need to save the `scripts` folder *within* the `src` directory. Various scripts use PonyGE packages located in `src`, and also interact with other scripts in `scripts`. Instead of constantly changing the path or adding new directories to the path, it just makes things a hell of a lot easier for everyone if we move the `scripts` folder inside the `src` directory. Everything works perfectly then.

This will not be an issue once PonyGE is an installable Python package, as we will be able to call it from everywhere. But this will require relative paths to be set, rather than `os.getcwd()`...
